#!/usr/bin/env bash
# Write a Bash script that loops from 1 to 10 and:
#displays bad luck for the 4th loop iteration

index=0

while [ $index -lt 10 ]
do
	if [ $index -eq 3 ]
	then
		echo "bad luck"
	elif [ $index -eq 7 ]
	then
		echo "good luck"
	else
		echo "Best School"
	fi
	(( index++ ))
done
